version: '3'

services:
  postgres-main:
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
    volumes:
      - postgres-db-main:/bitnami/postgres/data
    ports:
      - "5432:5432"

  postgres-test:
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=test

  app:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - "postgres-main"
      - "postgres-test"

volumes:
  postgres-db-main: